"""initial migration

Revision ID: 5ebd7bdda103
Revises: 
Create Date: 2025-11-01 00:41:15.475147

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = '5ebd7bdda103'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_embeddings',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('tokenized_at', sa.DateTime(), nullable=True),
    sa.Column('embedded_at', sa.DateTime(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('qdrant_collection', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('qdrant_point_ids', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_msg_embed_status_embedded', 'message_embeddings', ['status', 'embedded_at'], unique=False)
    op.create_index(op.f('ix_message_embeddings_content_sha256'), 'message_embeddings', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_message_embeddings_embedded_at'), 'message_embeddings', ['embedded_at'], unique=False)
    op.create_index(op.f('ix_message_embeddings_status'), 'message_embeddings', ['status'], unique=False)
    op.create_index(op.f('ix_message_embeddings_tokenized_at'), 'message_embeddings', ['tokenized_at'], unique=False)
    op.alter_column('channels', 'raw_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_channels_guild_id'), 'channels', ['guild_id'], unique=False)
    op.alter_column('guilds', 'raw_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('messages', 'raw_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_messages_author_id'), 'messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at_ms'), 'messages', ['created_at_ms'], unique=False)
    op.create_index(op.f('ix_messages_guild_id'), 'messages', ['guild_id'], unique=False)
    op.alter_column('users', 'raw_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'raw_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_messages_guild_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at_ms'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_author_id'), table_name='messages')
    op.alter_column('messages', 'raw_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('guilds', 'raw_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_channels_guild_id'), table_name='channels')
    op.alter_column('channels', 'raw_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_message_embeddings_tokenized_at'), table_name='message_embeddings')
    op.drop_index(op.f('ix_message_embeddings_status'), table_name='message_embeddings')
    op.drop_index(op.f('ix_message_embeddings_embedded_at'), table_name='message_embeddings')
    op.drop_index(op.f('ix_message_embeddings_content_sha256'), table_name='message_embeddings')
    op.drop_index('idx_msg_embed_status_embedded', table_name='message_embeddings')
    op.drop_table('message_embeddings')
    # ### end Alembic commands ###

