apiVersion: v2
name: discsync-embeddings
description: discsync-embeddings
type: application
version: 1.2.7
appVersion: 1.2.7
dependencies:
  - name: single-container
    version: "1.x.x"
    repository: "oci://ghcr.io/vaughnw128/charts"
