image: ghcr.io/vector3cyber/discsync-embeddings
containerPort: 8080

host: discsync-embeddings.internal.vw-ops.net

gateway:
  enabled: true
  className: cilium
  port: 80
  tls:
    enabled: true
    port: 443
    secretName: discsync-embeddings-tls

certManager:
  enabled: true
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare-issuer
  dnsNames:
    - discsync-embeddings.internal.vw-ops.net

envVars:
  EMBEDDING_MODEL: "text-embedding-qwen3-embedding-0.6b"
  EMBEDDING_BASE_URL: "http://localai-local-ai.applications.svc.cluster.local:80/v1"
  EMBEDDING_DIMENSIONS: "1024"
  EMBEDDING_API_KEY: "n/a"
  QDRANT_HOSTNAME: "http://qdrant.applications.svc.cluster.local"
  QDRANT_PORT: "443"
  QDRANT_COLLECTION: "discsync-embeddings"

db:
  enabled: true
  name: "sbux-oracle"
  cluster: "grove-cluster"

  migrator:
    secretName: "pg-migrator"

resources:
  requests:
    memory: 1024Mi
    cpu: 500m
  limits:
    memory: 4096Mi
    cpu: 4000m