name: Build and Release

on:
  workflow_run:
    workflows: ["Code Quality & Tests"]
    types: [completed]
    branches:
      - main

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: vaughnw128/hakoniwa/.github/workflows/build-and-release.yml@main
    with:
      platforms: linux/amd64,linux/arm64
    secrets: inherit

  bump:
    needs: build
    if: ${{ needs.build.outputs.new_version != '' }}
    uses: vaughnw128/hakoniwa/.github/workflows/bump.yml@main
    with:
      new_version: ${{ needs.build.outputs.new_version }}
      language: python
      helm-path: ./helm
      push-helm-oci: true
    secrets: inherit
